name = "embedded_rina_bin"
description = "Embedded RINA (Recursive InterNetwork Architecture) Stack in Ada"
version = "0.1.0-dev"

authors = ["Mason Ticehurst"]
maintainers = ["Mason Ticehurst <mft5293@psu.edu>"]
maintainers-logins = ["masonticehurst"]

executables = ["embedded_rina_bin"]
