name = "erina_tests"
description = "eRINA tests"
version = "0.1.0-dev"

authors = ["Mason Ticehurst"]
maintainers = ["Mason Ticehurst <masonticehurst@me.com>"]
maintainers-logins = ["masonticehurst"]

executables = ["erina_tests"]

[[depends-on]]
aunit = "^23.0.0"
erina_linux = "~0.1.0-dev"

[[pins]]
erina_linux = { path = "../eRINA_Linux" }

[build-switches]
"*".style_checks = "No"