name: Ada (GNAT)

on:
  push:
    paths:
      - '**.adb'
      - '**.ads'
      - '**.gpr'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild &&
        sudo apt-get install gcc g++ libprotobuf-dev protobuf-compiler cmake linux-headers-$(uname -r) python-is-python3 swig wpasupplicant hostapd &&
        git clone https://github.com/vmaffione/rlite.git &&
        cd rlite &&
        ./configure &&
        sudo make &&
        sudo make install depmod

    - name: Build
      run: gprbuild -j0 -p
