name: Ada (GNAT)

on:
  push:
    paths:
      - '**.adb'
      - '**.ads'
      - '**.gpr'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat gprbuild &&
        sudo apt-get install gcc g++ libprotobuf-dev protobuf-compiler cmake linux-headers-$(uname -r) python-is-python3 swig wpasupplicant hostapd &&
        git clone https://github.com/vmaffione/rlite.git &&
        cd rlite &&
        ./configure &&
        sudo make &&
        sudo make install depmod

    - name: Build
      run: gprbuild eRINA_Linux/erina_linux.gpr -j0 -p
    
    - name: Slack Notification Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://i.imgur.com/B8K3gi8.png
        SLACK_USERNAME: Build Bot
        SLACK_MESSAGE: 'Build Passed'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Slack Notification Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://i.imgur.com/B8K3gi8.png
        SLACK_USERNAME: Build Bot
        SLACK_MESSAGE: 'Build Failed'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}