name: STM32 Build

on:
  push:
    paths:
      - 'eRINA_STM32F7/**.adb'
      - 'eRINA_STM32F7/**.ads'
      - 'eRINA_STM32F7/**.gpr'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: alire-project/setup-alire@v2

    - name: Build
      run: >
        alr index --add git+https://github.com/GNAT-Academic-Program/alire-index --name gap &&
        cd eRINA_STM32F7 &&
        alr build
      
    - name: Slack Notification Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://i.imgur.com/B8K3gi8.png
        SLACK_USERNAME: Build Bot
        SLACK_MESSAGE: 'Build Passed'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Slack Notification Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://i.imgur.com/B8K3gi8.png
        SLACK_USERNAME: Build Bot
        SLACK_MESSAGE: 'Build Failed'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}